### ISSUE TITLE
Replace redux-undo with react-undo-redo

### ISSUE THREAD

**Issue by nlopin** [freenowtech/react-polygon-editor#19]
Migrate to React `useReducer` for undo-redo functionality. Currently we bring redux only for this.

https://github.com/frontendphil/react-undo-redo provides a nice API compatible with `redux-undo`

**Comment by dornelasnelson** [comment]
Redux-undo was replaced by react-undo-redo and merged to the /next branch in https://github.com/freenowtech/react-polygon-editor/pull/25
