### ISSUE TITLE
Consider Wave for icons/colors/etc

### ISSUE THREAD

**Issue by nlopin** [freenowtech/react-polygon-editor#22]
Experiment if it makes sense to use `@freenow/wave` for the library and what impact it has on the bundle size (currently 84kB in [Bundlephobia](https://bundlephobia.com/package/@freenow/react-polygon-editor@2.0.1))

**Comment by dornelasnelson** [comment]
I'm not 100% sure on this. If we aim on having a smaller bundle size we'd be going the other way around by adding wave. 

```
bundle-phobia @freenow/wave
ℹ @freenow/wave (1.34.4) has 12 dependencies for a weight of 716.38KB (158.67KB gzipped)
```

If `react-polygon-editor` is right now 84kb - going down when we merge the `next` branch swapping the undo-redo libs, while wave itself is 716.38KB, I think we can just add other two SVGs for the undo-redo buttons and keep the bundle small.

Checking other libraries, looks like we get in our lib something similar to the minified size of the lib inside of ours, so even that we'd have about 158.7 kB with the minified size of wave

What do you think?
